// generated by stringer -type=Flag; DO NOT EDIT

package pbo

import "fmt"

const (
	_Flag_name_0 = "FlagUncompressed"
	_Flag_name_1 = "FlagPacked"
	_Flag_name_2 = "FlagProductEntry"
)

var (
	_Flag_index_0 = [...]uint8{16}
	_Flag_index_1 = [...]uint8{10}
	_Flag_index_2 = [...]uint8{16}
)

func (i Flag) String() string {
	switch {
	case i == 0:
		return _Flag_name_0
	case i == 1131442803:
		return _Flag_name_1
	case i == 1449489011:
		return _Flag_name_2
	default:
		return fmt.Sprintf("Flag(%d)", i)
	}
}
